### PR TITLE
Feature address schema

### PR DESCRIPTION
**Pull request by BeatrizElena**
@randallmorey I'm assuming that although slowly, I'm on the right track as a newly minted repo contributor. 

I'm working on the bio feature but forgot to checkout a separate branch for it. I'll do it now.

### CODE REVIEW

**Comment by randallmorey** [comment]
@BeatrizElena try checking out `34e683e` and then create a ad push a new address branch from that.  Create a new PR when ready. I'm closing this PR in the meantime since it contains two separate things.

**Comment by randallmorey** [comment]
@BeatrizElena bio is being worked on by another contributor.  I assigned #20 to you instead.

**Comment by BeatrizElena** [comment]
I'm on branch 34e683e. What do you mean "and then create a ad push a new
address branch from that"? Does this mean that I will be pushing the branch
before I added the bio feature and, after closing the address issue, I can
checkout a new branch to work on issue #20?

**Comment by randallmorey** [comment]
Once you’re on the commit for the address schema, create a new branch with a new name and push it. Then create another pull request for that branch.

Since the existing address branch contains work for two different things, it cannot be used in a pull request. 

- Randall Morey

**Pull request closed without merging**
